{% set name = "nmslib" %}
{% set version = "2.1.1" %}

package:
  name: nmslib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nmslib/nmslib-{{ version }}.tar.gz
  sha256: 971294a7766f91c697d63c88c8adda4797a944346cc535a217393f4167a19c20
  patches:
    - patches/0001-remove-installation-requirements-handled-by-conda.patch

build:
  number: 0
  script: '{{ PYTHON }} -m pip install --no-deps --no-binary :all: .'

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - setuptools
    - psutil
    - pip
    - pybind11 >=2.2.3
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pybind11 >=2.2.3

test:
  imports:
    - nmslib

about:
  home: https://github.com/searchivarius/nmslib
  summary: Non-Metric Space Library (NMSLIB)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jzthree
    - h-vetinari
